/*
 * This file is generated by jOOQ.
 */
package com.pos.main.api.entities.tables;


import com.pos.main.api.entities.tables.tables.Author;


/**
 * Convenience access to all tables in library.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>library.author</code>.
     */
    public static final Author AUTHOR = Author.AUTHOR;
}
